# user defined exception

class Error(Exception):
	pass
class ValueTooMaximum(Error):
	pass